### ISSUE TITLE
Android: ACCESS_FINE_LOCATION permission required after NS ~6.1.0

### ISSUE THREAD

**Issue by msn444** [nativescript-community/ble#171]
As of NS 6.1.0 or so, ACCESS_COARSE_LOCATION is not sufficient to use BLE; ACCESS_FINE_LOCATION is required. The plugin does not request this permission, requiring the use of nativescript-permissions or other method to explicitly request ACCESS_FINE_LOCATION prior to use.

**Comment by facetious** [comment]
This isn't related to NS 6.1.0, but Android 10. If you deploy to Android 8, for example, the coarse location will still function correctly.

https://developer.android.com/about/versions/10/privacy/changes#location-telephony-bluetooth-wifi

(Note that I agree that this should be fixed in this library.)
